#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
功能：
1. 生成 Pocsuite3 通用 POC 模板
2. 提取 Suricata JSON 日志（eve.json）第一条流量信息
3. 将提取的信息填充到模板中，生成可用 POC
"""
import json
import os
from datetime import datetime

# ===================== 配置项（根据实际环境修改）=====================
# Suricata JSON 日志文件路径（默认路径）
SURICATA_LOG_PATH = "/var/log/suricata/eve.json"
# 生成的 POC 文件保存路径
GENERATED_POC_PATH = "suricata_generated_poc.py"
# 当前日期（用于填充模板）
CURRENT_DATE = datetime.now().strftime("%Y-%m-%d")

# ===================== 步骤1：定义 Pocsuite3 通用模板 =====================
POC_TEMPLATE = '''
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
POC 描述：从 Suricata 日志自动生成的漏洞检测脚本
生成时间：{generate_time}
Suricata 告警信息：{alert_message}
"""
from pocsuite3.api import (
    Output, POCBase, POC_CATEGORY, register_poc, requests,
    VUL_TYPE, OptString, logger
)

class SuricataAutoPOC(POCBase):
    # ========== 漏洞基础信息（从 Suricata 日志提取）==========
    vulID = '{vul_id}'          # Suricata 规则 SID
    version = '1.0'             # POC 版本
    author = 'AutoGenerated'    # 作者
    vulDate = '{vul_date}'      # 漏洞日期
    createDate = '{create_date}'# POC 创建日期
    updateDate = '{update_date}'# POC 更新日期
    references = []             # 参考链接
    name = '{poc_name}'         # POC 名称
    appPowerLink = ''           # 应用厂商链接
    appName = '{app_name}'      # 应用名称
    appVersion = '*'            # 影响版本
    vulType = {vul_type}        # 漏洞类型
    category = {poc_category}   # POC 分类
    desc = '''{poc_desc}'''     # 漏洞描述
    samples = {samples}         # 测试目标（从 Suricata 日志提取）
    install_requires = ['requests']

    # ========== 自定义参数 ==========
    def _options(self):
        o = [
            OptString('url', description='目标URL（格式：http://IP:端口）', required=True),
            OptString('payload', description='检测Payload', default='{payload}')
        ]
        return o

    # ========== 漏洞验证逻辑 ==========
    def _verify(self):
        result = {}
        url = self.get_option('url')
        payload = self.get_option('payload')
        target = f"{url.rstrip('/')}{payload}"

        try:
            # 构建请求头（从 Suricata 日志提取 User-Agent）
            headers = {{
                "User-Agent": "{user_agent}",
                "Accept": "*/*"
            }}

            # 根据 Suricata 日志选择请求方法（GET/POST）
            if "{http_method}" == "GET":
                response = requests.get(
                    target, headers=headers, timeout=5, verify=False, allow_redirects=False
                )
            else:
                response = requests.post(
                    target, headers=headers, timeout=5, verify=False, allow_redirects=False
                )

            # 漏洞验证规则（基础匹配，可根据实际需求扩展）
            if response.status_code == {status_code}:
                result['VerifyInfo'] = {{
                    'URL': target,
                    'Payload': payload,
                    'HTTP_Method': "{http_method}",
                    'Response_Status': response.status_code,
                    'Response_Content': response.text[:200]
                }}
        except Exception as e:
            logger.error(f"验证目标 {{url}} 失败：{{str(e)}}")

        return self.parse_output(result)

    # ========== 结果解析 ==========
    def parse_output(self, result):
        output = Output(self)
        if result:
            output.success(result)
        else:
            output.fail("目标未检测到该漏洞")
        return output

# 注册 POC
register_poc(SuricataAutoPOC)
'''

# ===================== 步骤2：提取 Suricata JSON 日志第一条信息 =====================
def extract_suricata_log(log_file):
    """
    提取 Suricata eve.json 日志中第一条告警流量信息
    :param log_file: Suricata JSON 日志路径
    :return: 提取的特征字典，无有效数据返回空字典
    """
    extracted_info = {
        "sid": "100000",  # 默认漏洞ID
        "alert_message": "Unknown Vulnerability",
        "dest_ip": "",
        "dest_port": 80,
        "http_uri": "",
        "http_method": "GET",
        "http_user_agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64) AppleWebKit/537.36",
        "category": "web-application-attack",
        "status_code": 200
    }

    # 读取日志文件并提取第一条告警数据
    if not os.path.exists(log_file):
        print(f"错误：Suricata 日志文件 {log_file} 不存在！")
        return {}

    with open(log_file, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                # 解析单条 JSON 日志
                log_data = json.loads(line)
                # 只处理告警事件（event_type=alert）
                if log_data.get("event_type") == "alert":
                    # 提取核心字段
                    extracted_info["sid"] = str(log_data["alert"].get("sid", extracted_info["sid"]))
                    extracted_info["alert_message"] = log_data["alert"].get("message", extracted_info["alert_message"])
                    extracted_info["dest_ip"] = log_data.get("dest_ip", "")
                    extracted_info["dest_port"] = log_data.get("dest_port", 80)
                    extracted_info["category"] = log_data["alert"].get("category", extracted_info["category"])

                    # 提取 HTTP 相关字段（如果存在）
                    if log_data.get("http"):
                        extracted_info["http_uri"] = log_data["http"].get("uri", "")
                        extracted_info["http_method"] = log_data["http"].get("method", "GET")
                        extracted_info["http_user_agent"] = log_data["http"].get("http_user_agent", extracted_info["http_user_agent"])
                        extracted_info["status_code"] = log_data["http"].get("status", 200)

                    print(f"成功提取第一条 Suricata 告警信息：{extracted_info['alert_message']}")
                    return extracted_info
            except json.JSONDecodeError:
                print(f"警告：无效的 JSON 行 - {line[:50]}...")
                continue
            except KeyError as e:
                print(f"警告：日志字段缺失 - {e}")
                continue

    print("警告：未在 Suricata 日志中找到告警事件！")
    return extracted_info

# ===================== 步骤3：填充模板并生成 POC 文件 =====================
def generate_poc(extracted_info):
    """
    将提取的日志信息填充到模板，生成可用的 POC 文件
    :param extracted_info: 提取的日志特征字典
    """
    if not extracted_info:
        print("错误：无有效日志信息，无法生成 POC！")
        return

    # 映射漏洞类型和 POC 分类（根据 Suricata 日志类别）
    vul_type_map = {
        "web-application-attack": "VUL_TYPE.WEB_APP_ATTACK",
        "sql-injection": "VUL_TYPE.INJECTION",
        "buffer-overflow": "VUL_TYPE.BUFFER_OVERFLOW",
        "protocol-error": "VUL_TYPE.PROTOCOL_ERROR"
    }
    poc_category_map = {
        "web-application-attack": "POC_CATEGORY.EXPLOITS.WEBAPP",
        "sql-injection": "POC_CATEGORY.EXPLOITS.WEBAPP",
        "buffer-overflow": "POC_CATEGORY.EXPLOITS.NETWORK",
        "protocol-error": "POC_CATEGORY.EXPLOITS.NETWORK"
    }

    # 模板参数替换
    poc_params = {
        "generate_time": CURRENT_DATE,
        "vul_id": extracted_info["sid"],
        "alert_message": extracted_info["alert_message"],
        "vul_date": CURRENT_DATE,
        "create_date": CURRENT_DATE,
        "update_date": CURRENT_DATE,
        "poc_name": f"Suricata_Alert_{extracted_info['alert_message']}",
        "app_name": "Web_Service",
        "vul_type": vul_type_map.get(extracted_info["category"], "VUL_TYPE.WEB_APP_ATTACK"),
        "poc_category": poc_category_map.get(extracted_info["category"], "POC_CATEGORY.EXPLOITS.WEBAPP"),
        "poc_desc": f"Suricata 检测到的漏洞：{extracted_info['alert_message']}\\n目标IP：{extracted_info['dest_ip']}\\n恶意路径：{extracted_info['http_uri']}",
        "samples": f"['http://{extracted_info['dest_ip']}:{extracted_info['dest_port']}']" if extracted_info["dest_ip"] else "[]",
        "payload": extracted_info["http_uri"],
        "user_agent": extracted_info["http_user_agent"],
        "http_method": extracted_info["http_method"],
        "status_code": extracted_info["status_code"]
    }

    # 填充模板并写入文件
    try:
        with open(GENERATED_POC_PATH, 'w', encoding='utf-8') as f:
            f.write(POC_TEMPLATE.format(**poc_params))
        print(f"✅ POC 文件已生成：{os.path.abspath(GENERATED_POC_PATH)}")
    except Exception as e:
        print(f"❌ 生成 POC 文件失败：{e}")

# ===================== 主函数 =====================
if __name__ == "__main__":
    # 1. 提取 Suricata 日志信息
    log_info = extract_suricata_log(SURICATA_LOG_PATH)
    
    # 2. 生成 POC 文件
    if log_info:
        generate_poc(log_info)
    
    # 3. 输出使用提示
    if os.path.exists(GENERATED_POC_PATH):
        print("\\n📌 使用说明：")
        print(f"1. 运行 POC 检测目标：pocsuite3 -r {GENERATED_POC_PATH} -u http://{log_info['dest_ip']}:{log_info['dest_port']} -v 2")
        print("2. 如需自定义 payload：pocsuite3 -r {GENERATED_POC_PATH} -u http://目标IP:端口 --payload '/自定义路径'")